<a href="https://colab.research.google.com/github/kunalburgul/Data_Analytics/blob/master/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Analytics**

## **Numpy Arrays**

**Python Objects:**

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing


In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)
print(np.arange(10)) # list or arrays from 0 to 9 

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [2]:
# Python Lists
L = range(1000)
%timeit [i**2 for i in L]

The slowest run took 7.81 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 259 µs per loop


In [3]:
 # Numpy array
a = np.arange(1000)
%timeit a**2

The slowest run took 174.60 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.42 µs per loop


### **Creating arrays**

#### **Manual Construction of arrays**

In [4]:
# Creating an 1_D array
a = np.array([0, 1, 2, 3])
a
%time

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.68 µs


In [5]:
# print dimensions
a.ndim

1

In [6]:
# shape
a.shape

(4,)

In [7]:
len(a)

4

In [8]:
# 2-D, 3-D Numpy array
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) #returns the size of the first dimention

2

In [12]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

Basically an,
- 1D array --> Vector
- 2D array --> Matrix
- **ND array --> Tensor**

#### **Functions for creating arrays** 

In [15]:
# Using arrange function
# arange is an array-valued version of the built-in Python range function
a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(1, 10, 2) #start, end (exclusive), step
b

array([1, 3, 5, 7, 9])

In [17]:
#using linspace that is n equal points
a = np.linspace(0, 1, 6) #start, end, n-number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
# common arrays for all ones in array
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# common arrays for all zeros in array
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c = np.eye(3) # Return a 2-D array with ones on diagonal and zeros elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
i = np.eye(3, 2)
i # 3 is number of rows, 2 is number of columns , index of diagonal start with 0


array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
# create array using diag function
a = np.diag([1, 2, 3, 4]) # construc a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
 np.diag(a)

array([1, 2, 3, 4])

In [24]:
# create a array using random and randn - rand normal
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4)
a

array([0.31570106, 0.00688013, 0.10130576, 0.45324126])

In [25]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***
a

array([ 1.21290348, -0.90865117, -1.5054631 ,  0.1698179 ])

**Note**
<br>
For random samples from N(\mu, \sigma^2), use:
sigma * np.random.randn(...) + mu

### **Basic DataTypes**

You may have noticed that, in some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2). This is due to a difference in the data-type used:

In [26]:
a = np.arange(10)
a.dtype

dtype('int64')

In [27]:
# You can explicitly specify which data-type you want:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
# The default data type is float for zeros and ones function
a = np.zeros((3, 3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

There are also other datatypes

In [29]:
d = np.array([1+2j, 2+4j])   #Complex datatype
print(d.dtype)

complex128


In [30]:
b = np.array([True, False, True, False])  #Boolean datatype
print(b.dtype)

bool


In [31]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

- 'b' − boolean
- 'i' − (signed) integer
- 'u' − unsigned integer
- 'f' − floating-point
- 'c' − complex-floating point
- 'm' − timedelta
- 'M' − datetime
- 'O' − (Python) objects
- 'S', 'a' − (byte-)string
- 'U' − Unicode
- 'V' − raw data (void)


**For more details:**
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

### **Indexing and Slicing**

#### **Indexing**

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [32]:
a = np.arange(10)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [33]:
# For multidimensional arrays, indexes are tuples of integers:
a = np.diag([1, 2, 3])
print(a[2, 2])

3


In [34]:
a[2, 1] = 5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

#### **Slicing**

In [35]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [37]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [38]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

### **Copies and Views**

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

When modifying the view, the original array is modified as well:

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [41]:
np.shares_memory(a, b)

True

In [42]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [43]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [44]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [45]:
np.shares_memory(a, c)

False

In [46]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Fancy Indexing**

NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views.

**Using Boolean Mask** 

In [47]:
a = np.random.randint(0, 20, 15)
a

array([16, 19, 16,  1,  6,  3, 18, 15, 15,  7,  4,  6,  9, 16,  5])

In [48]:
mask = (a % 2 == 0)

In [49]:
extract_from_a = a[mask]
extract_from_a

array([16, 16,  6, 18,  4,  6, 16])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [50]:
a[mask] = -1
a

array([-1, 19, -1,  1, -1,  3, -1, 15, 15,  7, -1, -1,  9, -1,  5])

**Indexing with an array of integers**

In [51]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [53]:
# New values can be assigned 
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])